<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <style></style>
  </head>
  <body>
    <script>
      // 10、Promise的链式调用
      // 11、then方法出错的时候会在下一个then里面拿到错误的原因
      // 12、then方法回调的是异步的
      // 13、then方法回调return的结果，一定能在下一个then的成功的回调接收
      const PENDING = 'pending'
      const FUFILLED = 'fulfilled'
      const REJECTED = 'rejected'
      class Promise {
        value
        reason
        status = PENDING
        onFulfilledCallBacks = []
        onRejectedCallBacks = []

        constructor(executor) {
          const resolve = (value) => {
            if (this.status === PENDING) {
              this.value = value
              this.status = FUFILLED
              this.onFulfilledCallBacks.forEach((cb) => cb())
            }
          }
          const reject = (reason) => {
            if (this.status === PENDING) {
              this.reason = reason
              this.status = REJECTED
              this.onRejectedCallBacks.forEach((cb) => cb())
            }
          }

          try {
            executor(resolve, reject)
          } catch (error) {
            reject(error)
          }
        }

        then(onFulfilled, onRejected) {
          // debugger
          const p2 = new Promise((resolve, reject) => {
            if (this.status === FUFILLED) {
              queueMicrotask(() => {
                try {
                  let x = onFulfilled(this.value)
                  resolve(x)
                } catch (error) {
                  reject(error)
                }
              })
            }

            if (this.status === REJECTED) {
              queueMicrotask(() => {
                try {
                  let x = onRejected(this.reason)
                  resolve(x)
                } catch (error) {
                  reject(error)
                }
              })
            }

            if (this.status === PENDING) {
              this.onFulfilledCallBacks.push(() => {
                queueMicrotask(() => {
                  try {
                    let x = onFulfilled(this.value)
                    resolve(x)
                  } catch (error) {
                    reject(error)
                  }
                })
              })

              this.onRejectedCallBacks.push(() => {
                queueMicrotask(() => {
                  try {
                    let x = onRejected(this.reason)
                    resolve(x)
                  } catch (error) {
                    reject(error)
                  }
                })
              })
            }
          })
          return p2
        }
      }
      // 示例12
      const p = new Promise((resolve, reject) => {
        // resolve('成功')
        reject()
      })
      p.then(
        () => {
          return '成功'
        },
        () => {
          return '失败'
        }
      ).then(
        (res) => {
          console.log('第二次then成功回调函数', res)
        },
        (error) => {
          console.log('第二次then失败回调函数', error)
        }
      )
      // 示例11：
      // const p = new Promise((resolve, reject) => {
      //   setTimeout(() => {
      //     resolve('成功')
      //   }, 1000)
      // })
      // p.then(
      //   (res) => {
      //     console.log(res, a.a)
      //   },
      //   () => {}
      // ).then(
      //   () => {},
      //   (error) => {
      //     console.log(error)
      //   }
      // )
      // 示例：10
      // const p = new Promise((resolve, reject) => {
      //   resolve('成功') // 同步情况
      // })

      // 10
      // p.then(
      //   () => {},
      //   () => {}
      // )
      //   .then(
      //     () => {},
      //     () => {}
      //   )
      //   .then(
      //     () => {},
      //     () => {}
      //   )
    </script>
  </body>
</html>
